"""Initial migration

Revision ID: 264c82bbe7fe
Revises: 
Create Date: 2026-08-20 23:23:49.477625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264c82bbe7fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('recipient_role', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('ack_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('resolution_code', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_cases_event_id'), 'alert_cases', ['event_id'], unique=False)
    op.create_index(op.f('ix_alert_cases_id'), 'alert_cases', ['id'], unique=False)
    op.create_table('farmer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_token', sa.String(), nullable=True),
    sa.Column('village_id', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('crop', sa.String(), nullable=True),
    sa.Column('sowing_date', sa.Date(), nullable=True),
    sa.Column('irrigation_type', sa.String(), nullable=True),
    sa.Column('area_band', sa.String(), nullable=True),
    sa.Column('phone_enc', sa.String(), nullable=True),
    sa.Column('consent_flags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_profiles_farmer_token'), 'farmer_profiles', ['farmer_token'], unique=True)
    op.create_index(op.f('ix_farmer_profiles_id'), 'farmer_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_farmer_profiles_village_id'), 'farmer_profiles', ['village_id'], unique=False)
    op.create_table('market_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=True),
    sa.Column('mandi_id', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('modal_price', sa.Float(), nullable=True),
    sa.Column('arrivals', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_quotes_commodity'), 'market_quotes', ['commodity'], unique=False)
    op.create_index(op.f('ix_market_quotes_id'), 'market_quotes', ['id'], unique=False)
    op.create_index(op.f('ix_market_quotes_mandi_id'), 'market_quotes', ['mandi_id'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('farmer_token', sa.String(), nullable=True),
    sa.Column('village_id', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('band', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('contributors', sa.JSON(), nullable=True),
    sa.Column('action_ids', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_event_id'), 'risk_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_risk_events_farmer_token'), 'risk_events', ['farmer_token'], unique=False)
    op.create_index(op.f('ix_risk_events_id'), 'risk_events', ['id'], unique=False)
    op.create_index(op.f('ix_risk_events_village_id'), 'risk_events', ['village_id'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('village_id', sa.String(), nullable=True),
    sa.Column('metric', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_observations_id'), 'weather_observations', ['id'], unique=False)
    op.create_index(op.f('ix_weather_observations_village_id'), 'weather_observations', ['village_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_observations_village_id'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_id'), table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index(op.f('ix_risk_events_village_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_farmer_token'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_event_id'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_market_quotes_mandi_id'), table_name='market_quotes')
    op.drop_index(op.f('ix_market_quotes_id'), table_name='market_quotes')
    op.drop_index(op.f('ix_market_quotes_commodity'), table_name='market_quotes')
    op.drop_table('market_quotes')
    op.drop_index(op.f('ix_farmer_profiles_village_id'), table_name='farmer_profiles')
    op.drop_index(op.f('ix_farmer_profiles_id'), table_name='farmer_profiles')
    op.drop_index(op.f('ix_farmer_profiles_farmer_token'), table_name='farmer_profiles')
    op.drop_table('farmer_profiles')
    op.drop_index(op.f('ix_alert_cases_id'), table_name='alert_cases')
    op.drop_index(op.f('ix_alert_cases_event_id'), table_name='alert_cases')
    op.drop_table('alert_cases')
    # ### end Alembic commands ###
