"""Add PostGIS, Audit, and Consent

Revision ID: 46b1c74fdd2b
Revises: 264c82bbe7fe
Create Date: 2026-08-21 00:00:49.621951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '46b1c74fdd2b'
down_revision: Union[str, Sequence[str], None] = '264c82bbe7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    is_postgres = op.get_bind().dialect.name == "postgresql"
    if is_postgres:
        op.execute('CREATE EXTENSION IF NOT EXISTS postgis')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_target_id'), 'audit_events', ['target_id'], unique=False)
    op.create_table('consent_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_token', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('proof', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_ledger_farmer_token'), 'consent_ledger', ['farmer_token'], unique=False)
    op.create_index(op.f('ix_consent_ledger_id'), 'consent_ledger', ['id'], unique=False)
    if is_postgres:
        op.create_table('mandis',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('mandi_id', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_mandis_id'), 'mandis', ['id'], unique=False)
        op.create_index(op.f('ix_mandis_mandi_id'), 'mandis', ['mandi_id'], unique=True)
        op.create_table('villages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('village_id', sa.String(), nullable=True),
        sa.Column('district_id', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_villages_district_id'), 'villages', ['district_id'], unique=False)
        op.create_index(op.f('ix_villages_id'), 'villages', ['id'], unique=False)
        op.create_index(op.f('ix_villages_village_id'), 'villages', ['village_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    is_postgres = op.get_bind().dialect.name == "postgresql"
    # ### commands auto generated by Alembic - please adjust! ###
    if is_postgres:
      op.drop_index(op.f('ix_villages_village_id'), table_name='villages')
      op.drop_index(op.f('ix_villages_id'), table_name='villages')
      op.drop_index(op.f('ix_villages_district_id'), table_name='villages')
      op.drop_index('idx_villages_location', table_name='villages', postgresql_using='gist')
      op.drop_table('villages')
      op.drop_index(op.f('ix_mandis_mandi_id'), table_name='mandis')
      op.drop_index(op.f('ix_mandis_id'), table_name='mandis')
      op.drop_index('idx_mandis_location', table_name='mandis', postgresql_using='gist')
      op.drop_table('mandis')
    op.drop_index(op.f('ix_consent_ledger_id'), table_name='consent_ledger')
    op.drop_index(op.f('ix_consent_ledger_farmer_token'), table_name='consent_ledger')
    op.drop_table('consent_ledger')
    op.drop_index(op.f('ix_audit_events_target_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
