"""Add outbox messages

Revision ID: 9de47203cf19
Revises: 46b1c74fdd2b
Create Date: 2026-08-21 00:09:01.151606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de47203cf19'
down_revision: Union[str, Sequence[str], None] = '46b1c74fdd2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('farmer_phone', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_log', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_messages_farmer_phone'), 'outbox_messages', ['farmer_phone'], unique=False)
    op.create_index(op.f('ix_outbox_messages_id'), 'outbox_messages', ['id'], unique=False)
    op.create_index(op.f('ix_outbox_messages_message_id'), 'outbox_messages', ['message_id'], unique=True)
    pass
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_villages_location', table_name='villages', postgresql_using='gist')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_outbox_messages_message_id'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_id'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_farmer_phone'), table_name='outbox_messages')
    op.drop_table('outbox_messages')
    # ### end Alembic commands ###
